### ISSUE TITLE
object patch size

### ISSUE THREAD

**Issue by ugurbolat** [zhen-he/tracking-by-animation#16]
Hello Zhen

First of all, I really liked your work and thanks for sharing. 

I am trying to train the net on another synthetic dataset where I have moving 3D objects with different sizes on the scene (instead of 2D objects in Sprite). And, I realized that you need to provide an object patch size (Y_{t,i}^a denoted in the paper). 

So my question is how can I set this patch size so that it can track objects with different sizes?

**Comment by zhen-he** [comment]
Hi Ugur,

Thanks for your interest.

The patch size is controlled by two parameters: the `scale` and the aspect `ratio` (Lines 66 and 67 in `modules/renderer.py`), and the range of these two parameters is controlled by `zeta_s` and `zeta_r` (Lines 240 and 241 in `scripts/gen_sprite.py`). Thus, you just need to (empirically) specify a range for the patch size by specifying `zeta_s` and `zeta_r`, and then the model can be trained to output the patch size falling into that range.

**Comment by ugurbolat** [comment]
I think I understand what `zeta_s` and `zeta_r[0]` do but could not figure out what `zeta_r[1]` does?

For example, if `zeta_r[0] = 0.5`, it would mean that the range of w:h would be 0.5, meaning if we have 50x50 (wxh) patch size, we would have the following ranges 25<w<50 and 50<h<75. 

However, it didn't get what `zeta_r[1]` does?

Or did I get `zeta_r` wrong? :/

**Comment by zhen-he** [comment]
`zeta_r[0]` and `zeta_r[1]` are the parameters specifying the range of w/h. As you can see from Line 67 in `modules/renderer.py`, the `ratio` on the RHS is the output of the tanh function and thus ranges from (-1, 1), which means the `ratio` on the LHS ranges from (`o.zeta_r[0]` - `o.zeta_r[1]`, `o.zeta_r[0]` + `o.zeta_r[1]`). This is more flexible as the range of the aspect ratio has 2 DOFs rather than 1. For instance, in real applications, if you observed the true aspect ratio ranges from (0.4, 1.2), then you can set `o.zeta_r[0]` = 0.8 and `o.zeta_r[1]` = 0.4.

**Comment by ugurbolat** [comment]
Thanks a lot, that clarifies all!
